rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'style-check'
    - 'docs'
    - 'unit (3.6)'
    - 'unit (3.6, cpp)'
    - 'unit (3.7)'
    - 'unit (3.7, cpp)'
    - 'unit (3.8)'
    # - 'unit (3.9, cpp)' # Don't have binary wheels for 3.9 cpp protobuf yet
    - 'unit (3.9)'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-python
    permission: push
  - team: actools
    permission: admin
  - team: actools-python
    permission: push
