rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: main
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'style-check'
    - 'docs'
    - 'unit (3.6)'
    - 'unit (3.6, cpp)'
    - 'unit (3.7)'
    - 'unit (3.7, cpp)'
    - 'unit (3.7, upb)'
    - 'unit (3.8)'
    - 'unit (3.8, cpp)'
    - 'unit (3.8, upb)'
    - 'unit (3.9)'
    - 'unit (3.9, cpp)'
    - 'unit (3.9, upb)'
    - 'unit (3.10)'
    - 'unit (3.10, cpp)'
    - 'unit (3.10, upb)'
    - 'unit (3.11)'
    - 'unit (3.11, upb)'
    - 'unit (3.12)'
    - 'unit (3.12, upb)'
    - cover
    - OwlBot Post Processor
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-python
    permission: push
  - team: actools
    permission: admin
  - team: actools-python
    permission: push
