---
version: 2
workflows:
  version: 2
  tests:
    jobs:
      - style-check:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
      - publish_package:
          requires:
            - style-check
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/
      - unit-3.6:
          filters:
            tags:
              only: /.*/
      - unit-cpp-3.6:
          filters:
            tags:
              only: /.*/
      - unit-3.7:
          filters:
            tags:
              only: /.*/
      - unit-cpp-3.7:
          filters:
            tags:
              only: /.*/
      - unit-3.8:
          filters:
            tags:
              only: /.*/
      - unit-cpp-3.8:
          filters:
            tags:
              only: /.*/
      - unit-3.9:
          filters:
            tags:
              only: /.*/
      # - unit-cpp-3.9:
      #     filters:
      #       tags:
      #         only: /.*/
      - docs:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - unit-3.6
            - unit-cpp-3.6
            - unit-3.7
            - unit-cpp-3.7
            - unit-3.8
            - unit-cpp-3.8
            - unit-3.9
            # - unit-cpp-3.9
            - docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+((a|b|rc)\d+)?$/
jobs:
  unit-3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.6
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-3.7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.7
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-3.8:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.8
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-3.9:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.9
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-3.10:
    docker:
      - image: python:3.10-rc
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.10
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-cpp-3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unitcpp-3.6
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-cpp-3.7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unitcpp-3.7
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-cpp-3.8:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install nox
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unitcpp-3.8
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  # unit-cpp-3.9:
  #   docker:
  #     - image: python:3.9
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install nox and codecov.
  #         command: |
  #           pip install nox
  #           pip install codecov
  #     - run:
  #         name: Run unit tests.
  #         command: nox -s unitcpp-3.9
  #     - run:
  #         name: Submit coverage data to codecov.
  #         command: codecov
  #         when: always
  docs:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install nox.
          command: pip install nox
      - run:
          name: Build the documentation.
          command: nox -s docs
  publish:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install twine
          command: |
            pip install twine
      - run:
          name: Build the package.
          command: python setup.py sdist
      - run:
          name: Publish to PyPI.
          command: twine upload dist/*

  style-check:
    docker:
      - image: python:3.8-slim
    steps:
      - checkout
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - run:
          name: Install black
          command: |
            pip install black==19.10b0
      - run:
          name: Format files
          command: |
            black .
      - run:
          name: Check diff
          command: |
            git diff --ignore-submodules=all --color --exit-code .
  publish_package:
    docker:
      - image: python:3.8-slim
    steps:
      - checkout
      - run:
          name: Install twine
          command: |
            pip install twine
      - run:
          name: Build the package.
          command: python setup.py sdist
      - run:
          name: Publish to PyPI.
          command: twine upload dist/*
